// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSVqCYu8B-pFhuicrULQtrga69QYp-qok',
    appId: '1:288227205093:web:3dd4039fbc1032d99b190c',
    messagingSenderId: '288227205093',
    projectId: 'locaition-7e0c2',
    authDomain: 'locaition-7e0c2.firebaseapp.com',
    databaseURL: 'https://locaition-7e0c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locaition-7e0c2.firebasestorage.app',
    measurementId: 'G-Y3KL3E1EHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_5ySLsynEKvhPh1K4xeeoNm1X5QSf3Yo',
    appId: '1:288227205093:android:82d00a16af7b93609b190c',
    messagingSenderId: '288227205093',
    projectId: 'locaition-7e0c2',
    databaseURL: 'https://locaition-7e0c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locaition-7e0c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRuRR90xDL3Idk9svVpR3x82kBitQMeyo',
    appId: '1:288227205093:ios:be315a150f1b59d99b190c',
    messagingSenderId: '288227205093',
    projectId: 'locaition-7e0c2',
    databaseURL: 'https://locaition-7e0c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locaition-7e0c2.firebasestorage.app',
    iosBundleId: 'com.example.locationTrackingv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRuRR90xDL3Idk9svVpR3x82kBitQMeyo',
    appId: '1:288227205093:ios:be315a150f1b59d99b190c',
    messagingSenderId: '288227205093',
    projectId: 'locaition-7e0c2',
    databaseURL: 'https://locaition-7e0c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locaition-7e0c2.firebasestorage.app',
    iosBundleId: 'com.example.locationTrackingv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSVqCYu8B-pFhuicrULQtrga69QYp-qok',
    appId: '1:288227205093:web:b82d1ee83d8089ab9b190c',
    messagingSenderId: '288227205093',
    projectId: 'locaition-7e0c2',
    authDomain: 'locaition-7e0c2.firebaseapp.com',
    databaseURL: 'https://locaition-7e0c2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'locaition-7e0c2.firebasestorage.app',
    measurementId: 'G-LKGWJ9Q3VV',
  );

}