// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYrYsyOvvhpKDu3A5PIHEznN4ERdJtKJk',
    appId: '1:9944351383:web:b864d0606b9432440a5fd2',
    messagingSenderId: '9944351383',
    projectId: 'location-895ab',
    authDomain: 'location-895ab.firebaseapp.com',
    storageBucket: 'location-895ab.firebasestorage.app',
    measurementId: 'G-TZN6K67TQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwI5pj1eIeHFWPfhPg8VSzJtwF8j2XGoc',
    appId: '1:9944351383:android:9ebcf0c7dd642bb00a5fd2',
    messagingSenderId: '9944351383',
    projectId: 'location-895ab',
    storageBucket: 'location-895ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJNlfCTxvQ7oucV_PBpqKv0ah1Y2-Skzk',
    appId: '1:9944351383:ios:a177df4d1fac36120a5fd2',
    messagingSenderId: '9944351383',
    projectId: 'location-895ab',
    storageBucket: 'location-895ab.firebasestorage.app',
    iosBundleId: 'com.example.locationTrackingv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJNlfCTxvQ7oucV_PBpqKv0ah1Y2-Skzk',
    appId: '1:9944351383:ios:a177df4d1fac36120a5fd2',
    messagingSenderId: '9944351383',
    projectId: 'location-895ab',
    storageBucket: 'location-895ab.firebasestorage.app',
    iosBundleId: 'com.example.locationTrackingv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYrYsyOvvhpKDu3A5PIHEznN4ERdJtKJk',
    appId: '1:9944351383:web:1078de21b227a6490a5fd2',
    messagingSenderId: '9944351383',
    projectId: 'location-895ab',
    authDomain: 'location-895ab.firebaseapp.com',
    storageBucket: 'location-895ab.firebasestorage.app',
    measurementId: 'G-1282LV0RC0',
  );
}
